{"name": "test_auth_invalid_data", "status": "passed", "description": "\n        Steps\n        1. Open main page\n        2. Auth with invalid data\n        3. Check auth result\n        ", "start": 1633100009633, "stop": 1633100011012, "uuid": "95f97483-b453-4ce7-8008-744698423de3", "historyId": "695f55378f8fe30fa2f217e0f6c38726", "testCaseId": "3288b5f502ddd6e63bc2e3b025925971", "fullName": "tests.auth.test_auth.TestAuth#test_auth_invalid_data", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "DESKTOP-N5LUFMH"}, {"name": "thread", "value": "14984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_auth"}]}
